spring:
  application:
    name: self-ai-agent
  ai:
    dashscope:
      api-key: "sk-ca52b11bade246f5977a4cc0d8b79aaf"
      chat:
        options:
          model: qwen-plus
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json
# searchApi
search-api:
  api-key: "sVVpWyaaRSmkyNeUhphD5aNT"
